# Blog info
blog_name: I/O - mvooer
slogan: Reading Writing Thinking
url: https://mvooer.me

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.png

# Set favicon
favicon: /favicon.ico

# For seo
keywords: forsigner,前端,设计,Hexo主题,前端开发,用户体验,设计,frontend,design,nodejs,JavaScript,mvooer,I/O - mvooer

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Github
    url: https://github.com/mvooer
    target_blank: true

# config page nav
page_nav:
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  #- name: 关于
  #  url: /about/
  #  target_blank: false
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开
  - name: 主页
    url: /
    target_blank: false # 不在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 首页

search_slogan:
  isShow: true # true|fase
  text: I've got you in my sights.

link_slogan:
  isShow: true # true|fase
  text:


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持forsigner
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: false # true|false
  showComments: false
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style:
#/css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
#baidu_analytics:

# Comment service
#disqus_shortname:
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# 注意，多说即将关闭，建议选用上面四个评论系统
# duoshuo_shortname: forsigner

# 不算子,文章访问量统计和显示
busuanzi: false

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "Scut，1991，Spring."
    - "喜欢设计，擅长编程，喜欢睡懒觉."
    - "前端开发工程师，常用 HTML / CSS / JavaScript."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@forsigner"
    text_value_url: https://github.com/forsigner
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@forsigner"
    text_value_url: http://weibo.com/u/1847075964
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "forsigner@gmail.com"
  - type: location
    icon: icon-location
    text_value: 珠海

link:
  - name: Halyul
    info: Never do a dreamer.
    url: https://halyul.cc/
    avatar: https://gravatar.com/userimage/113938008/e65085ec5e08a13de79873206f0c76fa.png?size=200
  - name: 萌咖
    info: 初心不忘
    url: https://moeclub.org/
    avatar: https://moeclub.org/favicon.ico
  - name: KeJun
    info: 二次元智障
    url: https://kejun.me
    avatar: https://ooo.0o0.ooo/2017/03/14/58c775b701fd8.png
  - name: mvooer
    info: (举个栗子)
    url: https://mvooer.me
    avatar: https://gravatar.cat.net/avatar/02965df580b7deca3037bc26c3a85d15?s=80


project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo